name: workflow.yml
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          clean: false

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Restart Server
        run: |
          pm2 delete KlubBilardowy || true
          pm2 start npm --name "KlubBilardowy" --cwd "${{ github.workspace }}" -- run preview
          pm2 save
